#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# OpenClaw → Claude Code Bridge
#
# Turns an OpenClaw workspace (a directory of markdown files describing
# identity, rules, voice, user, and tools) into a single unified CLAUDE.md
# that Claude Code reads on every session. Also configures Agent Teams and
# installs a tmux multi-pane launcher so you can run several Claude Code
# instances side-by-side and hand work between them.
#
# Expected OpenClaw workspace layout:
#   ~/.openclaw/workspace/AGENTS.md      — operational rules (RULES section)
#   ~/.openclaw/workspace/USER.md        — who the operator is
#   ~/.openclaw/workspace/IDENTITY.md    — the agent's identity
#   ~/.openclaw/workspace/SOUL.md        — voice, tone, philosophy
#   ~/.openclaw/workspace/TOOLS.md       — tools and services reference
#
# Run this script once to install the bridge. It also registers a cron job
# that re-syncs CLAUDE.md every 30 minutes so edits to the workspace files
# flow through to Claude Code automatically.
# ============================================================================

OC_WORKSPACE="${OC_WORKSPACE:-${HOME}/.openclaw/workspace}"
OC_CONFIG="${OC_CONFIG:-${HOME}/.openclaw/openclaw.json}"
CLAUDE_DIR="${HOME}/.claude"
CLAUDE_MD="${HOME}/CLAUDE.md"
BRIDGE_DIR="${HOME}/.openclaw/bridge"
BACKUP_SUFFIX="$(date +%Y%m%d-%H%M%S)"

echo "=== OpenClaw → Claude Code Bridge ==="
echo "Timestamp: $(date -Iseconds)"
echo ""

# ---- Pre-flight checks ----
for f in "${OC_WORKSPACE}/AGENTS.md" "${OC_WORKSPACE}/USER.md" "${OC_WORKSPACE}/IDENTITY.md" "${OC_WORKSPACE}/SOUL.md" "${OC_WORKSPACE}/TOOLS.md"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Missing $f"
        exit 1
    fi
done

if [[ ! -d "$CLAUDE_DIR" ]]; then
    echo "ERROR: ~/.claude not found. Is Claude Code installed?"
    exit 1
fi

mkdir -p "$BRIDGE_DIR"

# ---- Backup existing CLAUDE.md ----
if [[ -f "$CLAUDE_MD" ]]; then
    cp "$CLAUDE_MD" "${CLAUDE_MD}.bak.${BACKUP_SUFFIX}"
    echo "Backed up existing CLAUDE.md"
fi

# ---- Backup existing settings.json ----
if [[ -f "${CLAUDE_DIR}/settings.json" ]]; then
    cp "${CLAUDE_DIR}/settings.json" "${CLAUDE_DIR}/settings.json.bak.${BACKUP_SUFFIX}"
    echo "Backed up existing settings.json"
fi

# ============================================================================
# STEP 1: Generate CLAUDE.md from OpenClaw workspace
# ============================================================================
echo ""
echo "--- Step 1: Generating CLAUDE.md ---"

cat > "$CLAUDE_MD" << 'CLAUDE_HEADER'
# CLAUDE.md — Unified Workspace (OpenClaw + Claude Code)

This file is auto-generated by the OpenClaw bridge (`~/.openclaw/bridge/`).
Manual edits will be overwritten on next sync. Edit the source files instead.

## How This Works
You (Claude Code) share this machine with OpenClaw. Both systems can delegate
to each other. OpenClaw's workspace files are the source of truth for identity,
rules, memory, and operational context. This file synthesizes them for you.

CLAUDE_HEADER

# ---- Section: Identity ----
cat >> "$CLAUDE_MD" << 'EOF'
---

## Identity & Context

EOF

# Strip HTML comment markers as we concatenate each source file.
sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/IDENTITY.md" >> "$CLAUDE_MD"
echo "" >> "$CLAUDE_MD"

# ---- Section: User (operator) ----
cat >> "$CLAUDE_MD" << 'EOF'
---

## About the Operator

EOF
sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/USER.md" >> "$CLAUDE_MD"
echo "" >> "$CLAUDE_MD"

# ---- Section: Soul / Voice ----
cat >> "$CLAUDE_MD" << 'EOF'
---

## Voice & Philosophy

EOF
sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/SOUL.md" >> "$CLAUDE_MD"
echo "" >> "$CLAUDE_MD"

# ---- Section: Rules (from AGENTS.md) ----
# AGENTS.md is expected to have a "# RULES" section followed by a "# DELEGATION"
# section. We extract just the RULES portion — delegation is OpenClaw-internal
# and not relevant to a Claude Code session.
cat >> "$CLAUDE_MD" << 'EOF'
---

## Operational Rules

The following rules are imported from OpenClaw's AGENTS.md. They apply to
Claude Code sessions equally — especially security, config safety, and
credential handling.

EOF

awk '/^# RULES/,/^# DELEGATION/' "${OC_WORKSPACE}/AGENTS.md" | \
    sed '/^# DELEGATION/d; /^<!--/d; /^-->/d' >> "$CLAUDE_MD"
echo "" >> "$CLAUDE_MD"

# ---- Section: Tools quick reference ----
# TOOLS.md is expected to contain a "## Key services" section. We extract
# from there up to an optional "## Pending" marker (or EOF if absent).
cat >> "$CLAUDE_MD" << 'EOF'
---

## Tools & Services Quick Reference

EOF
awk '/^## Key services/,/^## Pending/' "${OC_WORKSPACE}/TOOLS.md" | \
    sed '/^## Pending/d; /^<!--/d; /^-->/d' >> "$CLAUDE_MD"
echo "" >> "$CLAUDE_MD"

# ---- Section: Claude Code + OpenClaw interop ----
cat >> "$CLAUDE_MD" << 'EOF'
---

## Claude Code ↔ OpenClaw Interop

### Shared filesystem
- OpenClaw workspace: `~/.openclaw/workspace/`
- OpenClaw memory: `~/.openclaw/memory/`
- OpenClaw config: `~/.openclaw/openclaw.json`
- Claude Code sessions: `~/.claude/sessions/`
- This file: `~/CLAUDE.md` (auto-generated, don't edit directly)

### How to use OpenClaw from Claude Code
OpenClaw exposes an OpenAI-compatible gateway on a loopback port. Check
`~/.openclaw/openclaw.json` for the exact port on your install, then:
```bash
curl -s http://127.0.0.1:<port>/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{"messages":[{"role":"user","content":"your message"}]}'
```

### How OpenClaw delegates to Claude Code
OpenClaw can spawn Claude Code subsessions via its ACP runtime. Those
sessions share the same filesystem as OpenClaw and can read/write the same
workspace files.

### Memory
OpenClaw keeps its own memory store under `~/.openclaw/memory/`. Claude
Code has its own memory system under `~/.claude/`. Both can read each
other's files — they just don't share an index.

### Sync
Run `bash ~/.openclaw/bridge/sync.sh` to regenerate this CLAUDE.md from
the current OpenClaw workspace. The installer also registers a cron job
that runs this every 30 minutes.

### Services
If you run OpenClaw or related services under `systemd --user`:
```bash
systemctl --user list-units --type=service --state=running
systemctl --user status <service>
systemctl --user restart <service>
```
EOF

CLAUDE_MD_SIZE=$(wc -c < "$CLAUDE_MD")
CLAUDE_MD_LINES=$(wc -l < "$CLAUDE_MD")
echo "Generated CLAUDE.md: ${CLAUDE_MD_LINES} lines, ${CLAUDE_MD_SIZE} bytes"

# ============================================================================
# STEP 2: Configure Claude Code settings.json for Agent Teams
# ============================================================================
echo ""
echo "--- Step 2: Configuring Claude Code settings ---"

cat > "${CLAUDE_DIR}/settings.json" << 'SETTINGS'
{
  "env": {
    "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS": "1",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "0"
  },
  "permissions": {
    "allow": [
      "Bash(find:*)",
      "Bash(cat:*)",
      "Bash(ls:*)",
      "Bash(head:*)",
      "Bash(tail:*)",
      "Bash(wc:*)",
      "Bash(grep:*)",
      "Bash(rg:*)",
      "Bash(sqlite3:*)",
      "Bash(curl:127.0.0.1*)",
      "Bash(python3:*)",
      "Bash(node:*)",
      "Bash(git:*)",
      "Bash(tmux:*)",
      "Bash(systemctl --user:*)",
      "Bash(journalctl --user:*)",
      "Read(*)",
      "Write(~/.openclaw/workspace/*)",
      "Write(~/.openclaw/memory/*)",
      "Write(~/CLAUDE.md)"
    ],
    "deny": [
      "Bash(rm -rf /*)",
      "Write(~/.openclaw/openclaw.json)"
    ]
  }
}
SETTINGS

echo "Wrote ${CLAUDE_DIR}/settings.json with Agent Teams enabled"

# ============================================================================
# STEP 3: Create the sync script (for cron)
# ============================================================================
echo ""
echo "--- Step 3: Creating sync script ---"

# Resolve where this installer lives so the sync script can re-invoke it.
BRIDGE_SCRIPT="$(readlink -f "$0")"

cat > "${BRIDGE_DIR}/sync.sh" << SYNC
#!/usr/bin/env bash
# Re-run the bridge to regenerate CLAUDE.md from the current OpenClaw workspace.
set -euo pipefail
exec bash "${BRIDGE_SCRIPT}" 2>&1 | tee -a "\${HOME}/.openclaw/bridge/sync.log"
SYNC
chmod +x "${BRIDGE_DIR}/sync.sh"

# ============================================================================
# STEP 4: Create tmux multi-pane session launcher
# ============================================================================
echo ""
echo "--- Step 4: Creating tmux session manager ---"

mkdir -p "${HOME}/bin"

cat > "${HOME}/bin/cc-teams" << 'TMUX_LAUNCHER'
#!/usr/bin/env bash
set -euo pipefail

# cc-teams — Launch Claude Code Agent Teams in tmux split panes
#
# Usage:
#   cc-teams                    # Start default 2-pane session
#   cc-teams 3                  # Start 3-pane session
#   cc-teams attach             # Reattach to existing session
#   cc-teams kill               # Kill the session

SESSION="cc-teams"
PANES="${1:-2}"
WORKDIR="${HOME}"

case "${1:-}" in
    attach)
        tmux attach-session -t "$SESSION" 2>/dev/null || echo "No session '$SESSION' running"
        exit 0
        ;;
    kill)
        tmux kill-session -t "$SESSION" 2>/dev/null && echo "Killed session '$SESSION'" || echo "No session to kill"
        exit 0
        ;;
    [1-9])
        PANES="$1"
        ;;
    "")
        PANES=2
        ;;
    *)
        echo "Usage: cc-teams [2-6|attach|kill]"
        exit 1
        ;;
esac

if tmux has-session -t "$SESSION" 2>/dev/null; then
    echo "Session '$SESSION' already exists. Use 'cc-teams attach' or 'cc-teams kill'"
    exit 1
fi

echo "Starting Claude Code Agent Teams with ${PANES} panes..."

tmux new-session -d -s "$SESSION" -c "$WORKDIR"
tmux send-keys -t "$SESSION" "claude" Enter

for ((i=2; i<=PANES; i++)); do
    if (( i % 2 == 0 )); then
        tmux split-window -h -t "$SESSION" -c "$WORKDIR"
    else
        tmux split-window -v -t "$SESSION" -c "$WORKDIR"
    fi
    tmux send-keys -t "$SESSION" "claude" Enter
done

tmux select-layout -t "$SESSION" tiled

echo "Session '$SESSION' ready with ${PANES} Claude Code instances."
echo "  cc-teams attach   — connect"
echo "  cc-teams kill     — stop all"
echo "  Shift+Down        — cycle between teammates (in Agent Teams mode)"

if [[ -t 0 ]]; then
    tmux attach-session -t "$SESSION"
fi
TMUX_LAUNCHER

chmod +x "${HOME}/bin/cc-teams"

# ============================================================================
# STEP 5: Create a quick-switch alias file
# ============================================================================
echo ""
echo "--- Step 5: Creating shell aliases ---"

cat > "${BRIDGE_DIR}/aliases.sh" << 'ALIASES'
# OpenClaw + Claude Code bridge aliases
# Source this in ~/.bashrc: source ~/.openclaw/bridge/aliases.sh

# Claude Code
alias cc='claude'
alias cct='cc-teams'
alias ccta='cc-teams attach'
alias cctk='cc-teams kill'

# OpenClaw
alias oc='cd ~/.openclaw && ls'
alias ocw='cd ~/.openclaw/workspace && ls'
alias ocm='cd ~/.openclaw/workspace/memory && ls'
alias ocservices='systemctl --user list-units --type=service --state=running'

# Sync bridge
alias ocsync='bash ~/.openclaw/bridge/sync.sh'

# Quick views
alias agents='cat ~/.openclaw/workspace/AGENTS.md | head -100'
alias soul='cat ~/.openclaw/workspace/SOUL.md'
alias claudemd='cat ~/CLAUDE.md | head -80'
ALIASES

echo "Created aliases at ${BRIDGE_DIR}/aliases.sh"

# ============================================================================
# STEP 6: Set up cron for periodic sync
# ============================================================================
echo ""
echo "--- Step 6: Setting up cron sync ---"

CRON_LINE="*/30 * * * * /usr/bin/bash ${BRIDGE_DIR}/sync.sh >> ${BRIDGE_DIR}/sync.log 2>&1"

if crontab -l 2>/dev/null | grep -qF "bridge/sync.sh"; then
    echo "Cron entry already exists, skipping"
else
    (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
    echo "Added cron: sync every 30 minutes"
fi

# ============================================================================
# Summary
# ============================================================================
echo ""
echo "============================================"
echo "  Bridge setup complete!"
echo "============================================"
echo ""
echo "Files created:"
echo "  ~/CLAUDE.md                         — unified context (${CLAUDE_MD_LINES} lines)"
echo "  ~/.claude/settings.json             — Agent Teams enabled + permissions"
echo "  ~/bin/cc-teams                      — tmux multi-pane launcher"
echo "  ~/.openclaw/bridge/aliases.sh       — shell aliases"
echo "  ~/.openclaw/bridge/sync.sh          — cron sync script"
echo ""
echo "Next steps:"
echo "  1. source ~/.openclaw/bridge/aliases.sh"
echo "     (add to ~/.bashrc for persistence)"
echo "  2. claude                            — single Claude Code session"
echo "  3. cc-teams 3                        — 3-pane Agent Teams session"
echo "  4. cc-teams attach                   — reattach from anywhere"
echo ""
echo "To add aliases permanently:"
echo '  echo "source ~/.openclaw/bridge/aliases.sh" >> ~/.bashrc'
echo ""
