#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# bridge.sh — OpenClaw → Claude Code CLAUDE.md synthesizer
#
# Reads the OpenClaw workspace markdown files and produces a single unified
# CLAUDE.md that Claude Code loads on every session.
#
# Usage:
#   bash bridge.sh sync          # regenerate ~/CLAUDE.md
#
# Environment overrides:
#   OC_WORKSPACE    default: ~/.openclaw/workspace
#   CLAUDE_MD_PATH  default: ~/CLAUDE.md
# ============================================================================

# Resolve the canonical OpenClaw home from this script's own location, NOT
# from $HOME. Secondary Claude harnesses (e.g. claude-b) run with HOME
# overridden to their own config dir, which would otherwise point OC_WORKSPACE
# at a nonexistent nested path. The script is always installed at
#   <OC_HOME>/.openclaw/bridge/lib/bridge.sh
# so we walk four levels up to recover <OC_HOME>.
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OC_HOME="${OC_HOME:-$(cd "${_SCRIPT_DIR}/../../.." && pwd)}"

OC_WORKSPACE="${OC_WORKSPACE:-${OC_HOME}/.openclaw/workspace}"
CLAUDE_MD="${CLAUDE_MD_PATH:-${OC_HOME}/CLAUDE.md}"
BRIDGE_DIR="${OC_HOME}/.openclaw/bridge"
BACKUP_SUFFIX="$(date +%Y%m%d-%H%M%S)"
CORE_DIR="${OC_HOME}/.openclaw/core"
NTK_READY=false
[[ -f "${CORE_DIR}/persona.md" && -f "${CORE_DIR}/rules-public.md" ]] && NTK_READY=true

REQUIRED_FILES=(
    "${OC_WORKSPACE}/IDENTITY.md"
    "${OC_WORKSPACE}/USER.md"
    "${OC_WORKSPACE}/SOUL.md"
    "${OC_WORKSPACE}/AGENTS.md"
    "${OC_WORKSPACE}/TOOLS.md"
)

CC_MEMORY_DIR="${OC_HOME}/.claude/projects/-home-openclaw/memory"
OC_WORKSPACE_MEMORY="${OC_WORKSPACE}/memory"

die() { echo "bridge.sh: $*" >&2; exit 1; }

check_prereqs() {
    for f in "${REQUIRED_FILES[@]}"; do
        [[ -f "$f" ]] || die "missing workspace file: $f"
    done
}

backup_existing() {
    if [[ -f "$CLAUDE_MD" ]]; then
        cp "$CLAUDE_MD" "${CLAUDE_MD}.bak.${BACKUP_SUFFIX}"
        # Keep only the last 5 backups to avoid clutter.
        ls -1t "${CLAUDE_MD}.bak."* 2>/dev/null | tail -n +6 | xargs -r rm -f
    fi
}

synthesize() {
    # Header
    cat > "$CLAUDE_MD" <<'HEADER'
# CLAUDE.md — Unified Workspace (OpenClaw + Claude Code)

This file is auto-generated by the OpenClaw bridge.
Manual edits will be overwritten on next sync. Edit the source files
in ~/.openclaw/workspace/ instead, then run `cc sync`.

## How This Works
You (Claude Code) share this machine with OpenClaw. Both systems can delegate
to each other. OpenClaw's workspace files are the source of truth for identity,
rules, memory, and operational context. This file synthesizes them for you.

HEADER

    # Identity
    {
        echo "---"
        echo ""
        echo "## Identity & Context"
        echo ""
        sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/IDENTITY.md"
        echo ""
    } >> "$CLAUDE_MD"

    # User (operator)
    {
        echo "---"
        echo ""
        echo "## About the Operator"
        echo ""
        sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/USER.md"
        echo ""
    } >> "$CLAUDE_MD"

    # Soul / Voice
    {
        echo "---"
        echo ""
        echo "## Voice & Philosophy"
        echo ""
        sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/SOUL.md"
        echo ""
    } >> "$CLAUDE_MD"

    # Rules — extract '# RULES' through '# DELEGATION' (exclusive)
    {
        echo "---"
        echo ""
        echo "## Operational Rules"
        echo ""
        echo "The following rules are imported from OpenClaw's AGENTS.md."
        echo "They apply to Claude Code sessions equally — especially security,"
        echo "config safety, and credential handling."
        echo ""
        awk '/^# RULES/,/^# DELEGATION/' "${OC_WORKSPACE}/AGENTS.md" \
            | sed '/^# DELEGATION/d; /^<!--/d; /^-->/d'
        echo ""
    } >> "$CLAUDE_MD"

    # Tools — extract '## Key services' through '## Pending' (exclusive)
    {
        echo "---"
        echo ""
        echo "## Tools & Services Quick Reference"
        echo ""
        awk '/^## Key services/,/^## Pending/' "${OC_WORKSPACE}/TOOLS.md" \
            | sed '/^## Pending/d; /^<!--/d; /^-->/d'
        echo ""
    } >> "$CLAUDE_MD"

    # Static interop section
    cat >> "$CLAUDE_MD" <<'INTEROP'
---

## Claude Code ↔ OpenClaw Interop

### Shared filesystem
- OpenClaw workspace: `~/.openclaw/workspace/`
- OpenClaw memory: `~/.openclaw/memory/`
- OpenClaw config: `~/.openclaw/openclaw.json`
- Claude Code sessions: `~/.claude/sessions/`
- This file: `~/CLAUDE.md` (auto-generated, don't edit directly)

### Running a team
Start a team session from your shell:

```bash
cc                 # start or attach the team tmux session
cc roles           # list available role presets
cc preset <name>   # print a preset prompt to paste into the lead
cc sync            # regenerate this file from the workspace
cc status          # show session / workspace status
```

Inside the session (prefix = `Ctrl-b`):
- `Ctrl-b B` — horizontal bars layout (stacked top-to-bottom)
- `Ctrl-b H` — vertical columns layout (side-by-side)
- `Ctrl-b T` — tiled layout
- Mouse wheel or `Shift+PageUp/Down` — scrollback (100k lines)
- `Alt+Arrow` — jump between panes
- `Ctrl-b d` — detach (session keeps running)

### Spawning teammates
Talk to the lead in plain English:

> create a team with 4 teammates in split-pane tmux mode.
> roles: researcher, backend, frontend, tests.
> assign non-overlapping file ownership so they don't clobber each other.

The lead creates the panes, spawns teammates, and routes work via an
internal `SendMessage` tool. You don't need to address teammates yourself —
talk to the lead.

### Sync
Automatic: every 30 minutes via cron (installed by `install.sh`).
Manual: `cc sync` or `bash ~/.openclaw/bridge/lib/bridge.sh sync`.
INTEROP

    local lines size
    lines=$(wc -l < "$CLAUDE_MD")
    size=$(wc -c < "$CLAUDE_MD")
    echo "generated CLAUDE.md: ${lines} lines, ${size} bytes"
}

# ── NeedToKnow scoped generation ─────────────────────────────────────────────

# synthesize_l0: minimal public bundle (persona + public rules only)
# Intended for Wire channel and untrusted callers.
synthesize_l0() {
    local out="${OC_HOME}/CLAUDE-l0.md"
    local tmp="${out}.tmp.$$"
    {
        cat <<'HDR'
# CLAUDE.md (L0 — Public/Untrusted Channel)

This session operates under public channel rules.
Only the Mr. Bernard public persona is available. No system details,
no operator identity, no infrastructure context.

---

HDR
        sed '/^<!--/d; /^-->/d' "${CORE_DIR}/persona.md"
        echo ""
        echo "---"
        echo ""
        sed '/^<!--/d; /^-->/d' "${CORE_DIR}/rules-public.md"
    } > "$tmp"
    mv "$tmp" "$out"
    local lines size
    lines=$(wc -l < "$out")
    size=$(wc -c < "$out")
    echo "generated CLAUDE-l0.md: ${lines} lines, ${size} bytes"
}

# create_l3_link: CLAUDE-l3.md → CLAUDE.md (same content, explicit label)
create_l3_link() {
    ln -sf "${CLAUDE_MD}" "${OC_HOME}/CLAUDE-l3.md"
    echo "linked CLAUDE-l3.md → CLAUDE.md"
}

# Keep sync.log bounded. Cron runs every 30 min and `cc` backgrounds extra syncs
# on startup, so the file grows monotonically without this. Truncate in place to
# the last 500 lines once it exceeds ~256 KB. Done inline (no logrotate dep).
rotate_log() {
    local log="${OC_HOME}/.openclaw/bridge/sync.log"
    [[ -f "$log" ]] || return 0
    local size
    size=$(wc -c < "$log" 2>/dev/null || echo 0)
    if (( size > 262144 )); then
        tail -n 500 "$log" > "${log}.tmp" && mv "${log}.tmp" "$log"
    fi
}

# ── Bidirectional memory sync ─────────────────────────────────────────────────

# sync_cc_to_oc: mirror Claude Code memory → OC workspace/memory/cc-memory/
# so cc-bridge sessions and OpenClaw agents can read CC's persistent facts.
sync_cc_to_oc() {
    [[ -d "$CC_MEMORY_DIR" ]] || return 0
    local dest="${OC_WORKSPACE_MEMORY}/cc-memory"
    mkdir -p "$dest"
    # Exclude the oc-memory/ subdir we write in the other direction (no loops)
    rsync -a --delete \
        --exclude='oc-memory/' \
        --exclude='oc-memory-index.md' \
        "${CC_MEMORY_DIR}/" "${dest}/"
    local count
    count=$(find "$dest" -name '*.md' | wc -l)
    echo "sync_cc_to_oc: ${count} files → workspace/memory/cc-memory/"
}

# sync_oc_to_cc: mirror key OC workspace memory → CC memory/oc-memory/
# Skips dated session logs (YYYY-MM-DD*.md) and large files (>50KB).
# Generates a MEMORY.md-compatible index file so CC sessions can find OC facts.
sync_oc_to_cc() {
    [[ -d "$OC_WORKSPACE_MEMORY" ]] || return 0
    local dest="${CC_MEMORY_DIR}/oc-memory"
    mkdir -p "$dest"
    # Sync only named .md files — skip dated session logs, transient reports, PII contacts
    # Use find+cp rather than rsync patterns (rsync char-classes are unreliable across versions)
    rm -f "${dest}"/*.md  # clear stale files before re-populating
    while IFS= read -r -d '' f; do
        local base
        base=$(basename "$f")
        # Skip: dated session logs (YYYY-MM-DD*.md), daily notes, portfolio reports, contact files
        [[ "$base" =~ ^[0-9]{4}-[0-9]{2} ]] && continue
        [[ "$base" =~ ^daily- ]] && continue
        [[ "$base" =~ portfolio-report ]] && continue
        [[ "$base" =~ ^contacts- ]] && continue
        cp -p "$f" "${dest}/${base}"
    done < <(find "${OC_WORKSPACE_MEMORY}" -maxdepth 1 -name '*.md' -print0)
    local count
    count=$(find "$dest" -maxdepth 1 -name '*.md' | wc -l)

    # Regenerate the CC-formatted index file so MEMORY.md can reference it.
    local index_file="${CC_MEMORY_DIR}/oc-memory-index.md"
    {
        cat <<'FRONT'
---
name: OpenClaw Memory Index
description: Key OC workspace memory files — facts, preferences, decisions, operational context, entities, servers, glucose profile
type: reference
---

OpenClaw workspace memory files are mirrored at `~/.claude/projects/-home-openclaw/memory/oc-memory/`.
Read specific files directly by path when you need detailed context.

## Key files

FRONT
        for f in "${dest}"/*.md; do
            [[ -f "$f" ]] || continue
            local name
            name=$(basename "$f" .md)
            local size
            size=$(wc -l < "$f")
            echo "- [\`${name}.md\`](oc-memory/${name}.md) — ${size} lines"
        done
        echo ""
        echo "Last synced: $(date -u '+%Y-%m-%d %H:%M UTC')"
    } > "$index_file"

    # Ensure MEMORY.md has an entry for oc-memory-index.md
    local memory_md="${CC_MEMORY_DIR}/MEMORY.md"
    if [[ -f "$memory_md" ]] && ! grep -q "oc-memory-index" "$memory_md"; then
        echo "- [OpenClaw Memory Index](oc-memory-index.md) — OC workspace: facts, preferences, decisions, operational context, entities" >> "$memory_md"
    fi

    echo "sync_oc_to_cc: ${count} files → memory/oc-memory/ + index updated"
}

case "${1:-sync}" in
    sync)
        # Serialize concurrent runs. Cron fires every 30 min; `cc`, `cc new`,
        # and `cc sync` can all background-kick the bridge, so three processes
        # racing on CLAUDE.md write + memory rsync is plausible. flock on a
        # dedicated lockfile keeps them single-file. -w 60 waits up to 60 s
        # before giving up; -E 0 makes the "couldn't acquire" exit be 0 so a
        # queued second cron run is silent rather than logging an error.
        LOCKFILE="${OC_HOME}/.openclaw/bridge/.sync.lock"
        exec 200>"$LOCKFILE"
        if ! flock -w 60 200; then
            echo "sync: another run holds the lock, skipping" >&2
            exit 0
        fi

        check_prereqs
        backup_existing
        synthesize
        sync_cc_to_oc
        sync_oc_to_cc
        rotate_log
        ;;
    sync-all)
        # Generates all scoped bundles: CLAUDE.md (L3) + CLAUDE-l0.md + CLAUDE-l3.md symlink.
        # Requires NTK directory structure (core/persona.md, core/rules-public.md).
        # Falls back to sync-only if NTK files are missing.
        LOCKFILE="${OC_HOME}/.openclaw/bridge/.sync.lock"
        exec 200>"$LOCKFILE"
        if ! flock -w 60 200; then
            echo "sync-all: another run holds the lock, skipping" >&2
            exit 0
        fi
        check_prereqs
        backup_existing
        synthesize
        sync_cc_to_oc
        sync_oc_to_cc
        if $NTK_READY; then
            synthesize_l0
            create_l3_link
            echo "sync-all: all scoped bundles generated"
        else
            echo "sync-all: NTK core files not ready, skipped scoped generation" >&2
        fi
        rotate_log
        ;;
    *)
        die "unknown command: $1 (try 'sync' or 'sync-all')"
        ;;
esac
