#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# bridge.sh — OpenClaw → Claude Code CLAUDE.md synthesizer
#
# Reads the OpenClaw workspace markdown files and produces a single unified
# CLAUDE.md that Claude Code loads on every session.
#
# Usage:
#   bash bridge.sh sync          # regenerate ~/CLAUDE.md
#
# Environment overrides:
#   OC_WORKSPACE    default: ~/.openclaw/workspace
#   CLAUDE_MD_PATH  default: ~/CLAUDE.md
# ============================================================================

OC_WORKSPACE="${OC_WORKSPACE:-${HOME}/.openclaw/workspace}"
CLAUDE_MD="${CLAUDE_MD_PATH:-${HOME}/CLAUDE.md}"
BRIDGE_DIR="${HOME}/.openclaw/bridge"
BACKUP_SUFFIX="$(date +%Y%m%d-%H%M%S)"

REQUIRED_FILES=(
    "${OC_WORKSPACE}/IDENTITY.md"
    "${OC_WORKSPACE}/USER.md"
    "${OC_WORKSPACE}/SOUL.md"
    "${OC_WORKSPACE}/AGENTS.md"
    "${OC_WORKSPACE}/TOOLS.md"
)

die() { echo "bridge.sh: $*" >&2; exit 1; }

check_prereqs() {
    for f in "${REQUIRED_FILES[@]}"; do
        [[ -f "$f" ]] || die "missing workspace file: $f"
    done
}

backup_existing() {
    if [[ -f "$CLAUDE_MD" ]]; then
        cp "$CLAUDE_MD" "${CLAUDE_MD}.bak.${BACKUP_SUFFIX}"
        # Keep only the last 5 backups to avoid clutter.
        ls -1t "${CLAUDE_MD}.bak."* 2>/dev/null | tail -n +6 | xargs -r rm -f
    fi
}

synthesize() {
    # Header
    cat > "$CLAUDE_MD" <<'HEADER'
# CLAUDE.md — Unified Workspace (OpenClaw + Claude Code)

This file is auto-generated by the OpenClaw bridge.
Manual edits will be overwritten on next sync. Edit the source files
in ~/.openclaw/workspace/ instead, then run `cc sync`.

## How This Works
You (Claude Code) share this machine with OpenClaw. Both systems can delegate
to each other. OpenClaw's workspace files are the source of truth for identity,
rules, memory, and operational context. This file synthesizes them for you.

HEADER

    # Identity
    {
        echo "---"
        echo ""
        echo "## Identity & Context"
        echo ""
        sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/IDENTITY.md"
        echo ""
    } >> "$CLAUDE_MD"

    # User (operator)
    {
        echo "---"
        echo ""
        echo "## About the Operator"
        echo ""
        sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/USER.md"
        echo ""
    } >> "$CLAUDE_MD"

    # Soul / Voice
    {
        echo "---"
        echo ""
        echo "## Voice & Philosophy"
        echo ""
        sed '/^<!--/d; /^-->/d' "${OC_WORKSPACE}/SOUL.md"
        echo ""
    } >> "$CLAUDE_MD"

    # Rules — extract '# RULES' through '# DELEGATION' (exclusive)
    {
        echo "---"
        echo ""
        echo "## Operational Rules"
        echo ""
        echo "The following rules are imported from OpenClaw's AGENTS.md."
        echo "They apply to Claude Code sessions equally — especially security,"
        echo "config safety, and credential handling."
        echo ""
        awk '/^# RULES/,/^# DELEGATION/' "${OC_WORKSPACE}/AGENTS.md" \
            | sed '/^# DELEGATION/d; /^<!--/d; /^-->/d'
        echo ""
    } >> "$CLAUDE_MD"

    # Tools — extract '## Key services' through '## Pending' (exclusive)
    {
        echo "---"
        echo ""
        echo "## Tools & Services Quick Reference"
        echo ""
        awk '/^## Key services/,/^## Pending/' "${OC_WORKSPACE}/TOOLS.md" \
            | sed '/^## Pending/d; /^<!--/d; /^-->/d'
        echo ""
    } >> "$CLAUDE_MD"

    # Static interop section
    cat >> "$CLAUDE_MD" <<'INTEROP'
---

## Claude Code ↔ OpenClaw Interop

### Shared filesystem
- OpenClaw workspace: `~/.openclaw/workspace/`
- OpenClaw memory: `~/.openclaw/memory/`
- OpenClaw config: `~/.openclaw/openclaw.json`
- Claude Code sessions: `~/.claude/sessions/`
- This file: `~/CLAUDE.md` (auto-generated, don't edit directly)

### Running a team
Start a team session from your shell:

```bash
cc                 # start or attach the team tmux session
cc roles           # list available role presets
cc preset <name>   # print a preset prompt to paste into the lead
cc sync            # regenerate this file from the workspace
cc status          # show session / workspace status
```

Inside the session (prefix = `Ctrl-b`):
- `Ctrl-b B` — horizontal bars layout (stacked top-to-bottom)
- `Ctrl-b H` — vertical columns layout (side-by-side)
- `Ctrl-b T` — tiled layout
- Mouse wheel or `Shift+PageUp/Down` — scrollback (100k lines)
- `Alt+Arrow` — jump between panes
- `Ctrl-b d` — detach (session keeps running)

### Spawning teammates
Talk to the lead in plain English:

> create a team with 4 teammates in split-pane tmux mode.
> roles: researcher, backend, frontend, tests.
> assign non-overlapping file ownership so they don't clobber each other.

The lead creates the panes, spawns teammates, and routes work via an
internal `SendMessage` tool. You don't need to address teammates yourself —
talk to the lead.

### Sync
Automatic: every 30 minutes via cron (installed by `install.sh`).
Manual: `cc sync` or `bash ~/.openclaw/bridge/lib/bridge.sh sync`.
INTEROP

    local lines size
    lines=$(wc -l < "$CLAUDE_MD")
    size=$(wc -c < "$CLAUDE_MD")
    echo "generated CLAUDE.md: ${lines} lines, ${size} bytes"
}

case "${1:-sync}" in
    sync)
        check_prereqs
        backup_existing
        synthesize
        ;;
    *)
        die "unknown command: $1 (try 'sync')"
        ;;
esac
